// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwcvsuvxmfiktcumntjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3Y3ZzdXZ4bWZpa3RjdW1udGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTI2MTcsImV4cCI6MjA2Mzc2ODYxN30.49M0G7e-us-nwuZRtXW1PJovevkm1yTqEGVvhMPzk7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);